require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('./models/Category');
const MenuItem = require('./models/MenuItem');
const Coupon = require('./models/Coupon');
const Faq = require('./models/Faq');
const Gallery = require('./models/Gallery');
const connectDB = require('./config/db');

const MOCK_CATEGORIES = [
  {
    "id": 1,
    "name": "Chai & Hot Teas",
    "icon": "Coffee",
    "displayOrder": 1
  },
  {
    "id": 2,
    "name": "Coffee & Brews",
    "icon": "Coffee",
    "displayOrder": 2
  },
  {
    "id": 3,
    "name": "Thick Milkshakes",
    "icon": "CupSoda",
    "displayOrder": 3
  },
  {
    "id": 4,
    "name": "Boba Tea Series",
    "icon": "Sparkles",
    "displayOrder": 4
  },
  {
    "id": 5,
    "name": "Matcha Series",
    "icon": "Leaf",
    "displayOrder": 5
  },
  {
    "id": 6,
    "name": "Sandwiches & Toasts",
    "icon": "Utensils",
    "displayOrder": 6
  },
  {
    "id": 7,
    "name": "Burgers & Fries",
    "icon": "Flame",
    "displayOrder": 7
  },
  {
    "id": 8,
    "name": "Crispy Appetisers",
    "icon": "Sparkles",
    "displayOrder": 8
  },
  {
    "id": 9,
    "name": "Noodles & Chowmein",
    "icon": "Utensils",
    "displayOrder": 9
  },
  {
    "id": 10,
    "name": "Fried Rice & Cutlets",
    "icon": "Bowl",
    "displayOrder": 10
  },
  {
    "id": 11,
    "name": "Cold Drinks & Coolers",
    "icon": "Wine",
    "displayOrder": 11
  },
  {
    "id": 12,
    "name": "Traditional Lassi",
    "icon": "CupSoda",
    "displayOrder": 12
  },
  {
    "id": 13,
    "name": "Frappes & Ice Cream",
    "icon": "IceCream",
    "displayOrder": 13
  },
  {
    "id": 14,
    "name": "Artisanal Italian Pasta",
    "icon": "Pizza",
    "displayOrder": 14
  },
  {
    "id": 99,
    "name": "Add-ons & Extras",
    "icon": "PlusCircle",
    "displayOrder": 15
  }
];

const MOCK_MENU_ITEMS = [
  {
    "id": 101,
    "categoryId": 1,
    "name": "Masala Tea",
    "description": "Our signature kadak chai infused with hand-crushed green cardamom, cloves, cinnamon, fresh ginger, and premium CTC tea leaves brewed in creamy whole milk.",
    "price": 40,
    "imageUrl": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": true,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 5,
    "calories": 120,
    "rating": 4.98,
    "reviewCount": 520,
    "ingredients": [
      "CTC Tea Leaves",
      "Green Cardamom",
      "Ginger",
      "Cloves",
      "Cinnamon",
      "Full Cream Milk"
    ],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 102,
    "categoryId": 1,
    "name": "Lemon Tea",
    "description": "Bright and invigorating golden black tea infused with freshly squeezed lemon juice, mint, and a touch of natural honey.",
    "price": 50,
    "imageUrl": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 45,
    "rating": 4.85,
    "reviewCount": 180,
    "ingredients": [
      "Black Tea Leaves",
      "Fresh Lemon Juice",
      "Mint Leaves",
      "Organic Honey"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 103,
    "categoryId": 1,
    "name": "Darjeeling Black Tea",
    "description": "First-flush Muscatel Darjeeling tea leaves steeped to amber perfection, offering a delicate floral aroma and brisk clean finish.",
    "price": 60,
    "imageUrl": "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 10,
    "rating": 4.9,
    "reviewCount": 210,
    "ingredients": [
      "Single-Estate Darjeeling Tea Leaves",
      "Filtered Water"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 104,
    "categoryId": 1,
    "name": "Honey Ginger Black Tea",
    "description": "Soothing hot immunity tea brewed with crushed organic ginger root, wild honey, and whole black tea leaves.",
    "price": 70,
    "imageUrl": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 5,
    "calories": 60,
    "rating": 4.92,
    "reviewCount": 195,
    "ingredients": [
      "Fresh Ginger Root",
      "Wild Honey",
      "Black Tea Leaves",
      "Lemon Slice"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 105,
    "categoryId": 1,
    "name": "Peach Ice Tea",
    "description": "Slow-steeped iced black tea muddled with sweet peach nectar, mint sprigs, and crushed ice for a crisp, fruity summer refresher.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 110,
    "rating": 4.95,
    "reviewCount": 310,
    "ingredients": [
      "Steeped Black Tea",
      "Peach Puree",
      "Fresh Mint",
      "Crushed Ice",
      "Lemon Wheel"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 201,
    "categoryId": 2,
    "name": "Cappuccino",
    "description": "Full-bodied dark roast espresso pulled fresh, topped with equal parts steamed milk and thick velvety micro-foam dusted with cocoa.",
    "price": 90,
    "imageUrl": "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 140,
    "rating": 4.9,
    "reviewCount": 340,
    "ingredients": [
      "Arabica Espresso",
      "Steamed Whole Milk",
      "Milk Foam",
      "Cocoa Dust"
    ],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 202,
    "categoryId": 2,
    "name": "Cold Coffee",
    "description": "Creamy classic blended iced coffee whipped with rich espresso, chilled milk, vanilla essence, and chocolate drizzle.",
    "price": 90,
    "imageUrl": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 210,
    "rating": 4.95,
    "reviewCount": 520,
    "ingredients": [
      "Espresso",
      "Chilled Whole Milk",
      "Vanilla Syrup",
      "Chocolate Syrup",
      "Ice"
    ],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 203,
    "categoryId": 2,
    "name": "Espresso",
    "description": "A bold, intense 30ml shot of 100% Arabica coffee extracted under 9 bars of pressure with a thick golden crema.",
    "price": 50,
    "imageUrl": "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 2,
    "calories": 5,
    "rating": 4.8,
    "reviewCount": 110,
    "ingredients": [
      "Freshly Ground Arabica Coffee Beans"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 204,
    "categoryId": 2,
    "name": "Espresso Tonic",
    "description": "A bubbly, bold specialty drink pairing a double shot of espresso poured over chilled sparkling tonic water, ice, and rosemary sprig.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 3,
    "calories": 75,
    "rating": 4.88,
    "reviewCount": 160,
    "ingredients": [
      "Double Espresso",
      "Botanical Tonic Water",
      "Rosemary",
      "Crystal Ice"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 205,
    "categoryId": 2,
    "name": "Americano",
    "description": "Simple, strong, and pure double espresso diluted with hot filtered water, highlighting smooth nutty and dark chocolate notes.",
    "price": 50,
    "imageUrl": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 3,
    "calories": 10,
    "rating": 4.75,
    "reviewCount": 130,
    "ingredients": [
      "Double Shot Espresso",
      "Hot Filtered Water"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 206,
    "categoryId": 2,
    "name": "Iced Americano",
    "description": "Chilled double espresso poured over crystal ice and cold water for a crisp, clean caffeine kick.",
    "price": 70,
    "imageUrl": "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 3,
    "calories": 10,
    "rating": 4.82,
    "reviewCount": 175,
    "ingredients": [
      "Double Espresso",
      "Chilled Water",
      "Ice Cubes"
    ],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 207,
    "categoryId": 2,
    "name": "Iced Spanish Latte",
    "description": "Sweet, smooth, and indulgent espresso layered over sweetened condensed milk and chilled whole milk over ice.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 240,
    "rating": 4.96,
    "reviewCount": 410,
    "ingredients": [
      "Espresso",
      "Sweetened Condensed Milk",
      "Chilled Milk",
      "Ice"
    ],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 208,
    "categoryId": 2,
    "name": "Iced Caramel Macchiato",
    "description": "Layered delight featuring vanilla-infused cold milk, freshly pulled espresso float, and a generous drizzle of homemade salted caramel.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 260,
    "rating": 4.94,
    "reviewCount": 380,
    "ingredients": [
      "Vanilla Syrup",
      "Cold Milk",
      "Espresso",
      "Salted Caramel Drizzle",
      "Ice"
    ],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 209,
    "categoryId": 2,
    "name": "Affogato",
    "description": "Decadent coffee meets dessert: a scoop of velvety Madagascar vanilla ice cream drowned in a hot shot of fresh espresso.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1592663527359-cf6642f54cff?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 3,
    "calories": 180,
    "rating": 4.92,
    "reviewCount": 220,
    "ingredients": [
      "Vanilla Bean Ice Cream",
      "Hot Fresh Espresso Shot"
    ],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 301,
    "categoryId": 3,
    "name": "Butterscotch Cream Shake",
    "description": "Classic buttery caramelized butterscotch blended with thick dairy cream and crunchy praline butterscotch bits.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 340,
    "rating": 4.9,
    "reviewCount": 280,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 302,
    "categoryId": 3,
    "name": "Banana Honey Cream Shake",
    "description": "Ripe bananas blended smoothly with pure wild honey, rich dairy cream, and chilled milk for a velvety wholesome shake.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 310,
    "rating": 4.88,
    "reviewCount": 190,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 303,
    "categoryId": 3,
    "name": "Pineapple Delight Shake",
    "description": "Tropical sweet pineapple puree blended with smooth vanilla cream and ice for a refreshing dessert shake.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 290,
    "rating": 4.82,
    "reviewCount": 160,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 304,
    "categoryId": 3,
    "name": "Mango Magic Shake",
    "description": "Real Alphonso mango pulp churned with rich dairy cream, pure tropical bliss in every thick golden sip.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 330,
    "rating": 4.96,
    "reviewCount": 430,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 305,
    "categoryId": 3,
    "name": "Oreo Blast Shake",
    "description": "Crunchy chocolate Oreo cookies crushed and blended with rich vanilla cream, dark chocolate drizzle, and Oreo crumb topping.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 420,
    "rating": 4.98,
    "reviewCount": 620,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 306,
    "categoryId": 3,
    "name": "Kitkat Crunch Shake",
    "description": "Your favourite crispy wafer chocolate break blended into a thick, chocolaty milkshake topped with KitKat fingers.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 410,
    "rating": 4.95,
    "reviewCount": 510,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 307,
    "categoryId": 3,
    "name": "Chocolate Overload Shake",
    "description": "For the true chocolate lover: Belgian cocoa, dark fudge sauce, chocolate chips, and thick cream blended to rich perfection.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 440,
    "rating": 4.97,
    "reviewCount": 480,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 308,
    "categoryId": 3,
    "name": "Strawberry Delight Shake",
    "description": "Sweet ripe strawberries pureed and blended with creamy vanilla soft serve for a vibrant pink indulgence.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 320,
    "rating": 4.9,
    "reviewCount": 270,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 309,
    "categoryId": 3,
    "name": "Blueberry Cream Shake",
    "description": "Wild blueberries blended with smooth rich cream, delivering an exquisite balance of sweet and tangy berry goodness.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1626078436892-0f04f2f4e8b3?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 330,
    "rating": 4.92,
    "reviewCount": 290,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 401,
    "categoryId": 4,
    "name": "Nutty Taro Boba Tea",
    "description": "Velvety sweet purple taro root milk tea paired with juicy popping litchi boba pearls over crushed ice.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1558857563-b37cf5a84277?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 280,
    "rating": 4.94,
    "reviewCount": 320,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 402,
    "categoryId": 4,
    "name": "Coffee Mocha Boba Tea",
    "description": "Cold brewed espresso and rich chocolate mocha milk tea topped with chewy popping chocolate boba pearls.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 290,
    "rating": 4.91,
    "reviewCount": 280,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 403,
    "categoryId": 4,
    "name": "Blueberry Boba Tea",
    "description": "Refreshing blueberry-infused iced milk tea loaded with burst-in-the-mouth litchi popping boba.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 260,
    "rating": 4.93,
    "reviewCount": 310,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 404,
    "categoryId": 4,
    "name": "Matcha Boba Tea",
    "description": "Authentic stone-ground Japanese Uji matcha whisked with chilled milk, served over decadent chocolate popping boba pearls.",
    "price": 190,
    "imageUrl": "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 270,
    "rating": 4.97,
    "reviewCount": 410,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 405,
    "categoryId": 4,
    "name": "Hazelnut Boba Tea",
    "description": "Aromatic roasted hazelnut milk tea paired with chewy chocolate popping boba for a nutty, chocolatey finish.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 285,
    "rating": 4.9,
    "reviewCount": 250,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Nuts"
    ],
    "customizationGroups": []
  },
  {
    "id": 501,
    "categoryId": 5,
    "name": "Iced Matcha Latte",
    "description": "Smooth, vibrant ceremonial Japanese matcha freshly whisked and poured over chilled whole milk and ice.",
    "price": 220,
    "imageUrl": "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 190,
    "rating": 4.93,
    "reviewCount": 350,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 502,
    "categoryId": 5,
    "name": "Vanilla Matcha Latte",
    "description": "Creamy Madagascar vanilla bean extract blended with premium green matcha and steamed or chilled silky milk.",
    "price": 260,
    "imageUrl": "https://images.unsplash.com/photo-1546889988-d63c5a610443?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 220,
    "rating": 4.95,
    "reviewCount": 290,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 503,
    "categoryId": 5,
    "name": "Strawberry Matcha Latte",
    "description": "Stunning aesthetic layered drink: housemade fresh strawberry puree at the bottom, chilled milk in the middle, and rich whisked matcha on top.",
    "price": 280,
    "imageUrl": "https://images.unsplash.com/photo-1558857563-b37cf5a84277?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 240,
    "rating": 4.99,
    "reviewCount": 580,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 504,
    "categoryId": 5,
    "name": "Mango Matcha Latte",
    "description": "Sweet golden Alphonso mango compote layered with cold milk and crowned with freshly whisked smooth Japanese matcha.",
    "price": 270,
    "imageUrl": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 230,
    "rating": 4.96,
    "reviewCount": 340,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 601,
    "categoryId": 6,
    "name": "Veg Cheese Sandwich",
    "description": "Freshly sliced garden cucumbers, tomatoes, capsicum, and melted mozzarella cheese seasoned with herb butter in golden toasted bread. (Served with crispy Fries).",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 380,
    "rating": 4.88,
    "reviewCount": 390,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 602,
    "categoryId": 6,
    "name": "Veg Cheese Corn Sandwich",
    "description": "Sweet tender American corn kernels smothered in creamy cheddar and mozzarella cheese with mild spices, grilled crisp. (Served with crispy Fries).",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 420,
    "rating": 4.92,
    "reviewCount": 460,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 603,
    "categoryId": 6,
    "name": "Chicken Cheese Sandwich",
    "description": "Juicy shredded chicken breast seasoned in house garlic herbs, layered with melted mozzarella and toasted golden brown. (Served with crispy Fries).",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1567234669003-dce7a7a88821?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 10,
    "calories": 460,
    "rating": 4.94,
    "reviewCount": 510,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 604,
    "categoryId": 6,
    "name": "Tandoori Chicken Cheese Sandwich",
    "description": "Smoky clay-oven tandoori chicken tikka chunks tossed with spiced mayo, crisp onions, and melted cheese on toasted jumbo bread. (Served with crispy Fries).",
    "price": 140,
    "imageUrl": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 2,
    "preparationTimeMinutes": 10,
    "calories": 510,
    "rating": 4.97,
    "reviewCount": 680,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 701,
    "categoryId": 7,
    "name": "Veg Cheese Burger",
    "description": "Golden spiced vegetable and potato patty topped with a slice of melted American cheese, lettuce, tomato, and special herb mayo in a toasted sesame bun. (Served with Fries).",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 10,
    "calories": 480,
    "rating": 4.86,
    "reviewCount": 320,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 702,
    "categoryId": 7,
    "name": "Chicken Cheese Burger",
    "description": "Crispy fried chicken breast fillet glazed in house secret sauce, topped with melted cheese, gherkins, and crunchy lettuce. (Served with Fries).",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 10,
    "calories": 560,
    "rating": 4.95,
    "reviewCount": 610,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 703,
    "categoryId": 7,
    "name": "Chicken Double Patty Cheese Burger",
    "description": "Double the chicken patties, double the melted cheese slices, layered with special burger relish and caramelized onions in a soft brioche bun. (Served with Fries).",
    "price": 160,
    "imageUrl": "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 12,
    "calories": 720,
    "rating": 4.98,
    "reviewCount": 740,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 704,
    "categoryId": 7,
    "name": "Salted Classic French Fries",
    "description": "Crispy, golden-fried potato batons lightly tossed with sea salt, served piping hot with tomato ketchup and garlic mayo.",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 6,
    "calories": 310,
    "rating": 4.88,
    "reviewCount": 450,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 705,
    "categoryId": 7,
    "name": "Peri Peri Fries",
    "description": "Crispy golden french fries tossed generously in our spicy, tangy African Bird Eye Peri-Peri seasoning.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 2,
    "preparationTimeMinutes": 6,
    "calories": 320,
    "rating": 4.93,
    "reviewCount": 580,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 706,
    "categoryId": 7,
    "name": "Loaded Fries",
    "description": "Mountain of crispy golden fries drenched in warm molten cheese sauce, spicy garlic mayo, diced jalapeños, and fresh herbs.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 8,
    "calories": 490,
    "rating": 4.96,
    "reviewCount": 620,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 801,
    "categoryId": 8,
    "name": "Veg Cheese Corn Nuggets (8 pcs)",
    "description": "Crispy golden-crumbed bite-sized nuggets filled with sweet corn and melted gooey cheese, served with sweet chilli dip.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 340,
    "rating": 4.9,
    "reviewCount": 310,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 802,
    "categoryId": 8,
    "name": "Paneer Pops (10 pcs)",
    "description": "Soft cubes of fresh cottage cheese coated in a crunchy spiced batter and deep-fried to golden perfection, served with mint dip.",
    "price": 160,
    "imageUrl": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 390,
    "rating": 4.92,
    "reviewCount": 380,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 803,
    "categoryId": 8,
    "name": "Cheesy Pizza Fingers",
    "description": "All the savory flavours of an Italian pizza enclosed in a crispy golden finger roll, bursting with molten mozzarella and oregano.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 360,
    "rating": 4.91,
    "reviewCount": 290,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 804,
    "categoryId": 8,
    "name": "Potato Cheese Bites",
    "description": "Crisp seasoned mashed potato spheres filled with a warm melted cheddar heart, served with tangy salsa dip.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 330,
    "rating": 4.89,
    "reviewCount": 260,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 805,
    "categoryId": 8,
    "name": "Paneer Chilly (8 pcs)",
    "description": "Wok-tossed crispy paneer cubes in a spicy, tangy Indo-Chinese dark soya and chilli garlic sauce with crunchy capsicum and onions.",
    "price": 250,
    "imageUrl": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 2,
    "preparationTimeMinutes": 12,
    "calories": 480,
    "rating": 4.95,
    "reviewCount": 520,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 806,
    "categoryId": 8,
    "name": "Chicken Pakora (8 pcs)",
    "description": "Classic Kolkata-style crispy chicken fritters marinated in ginger, garlic, and freshly roasted spices, fried crunchy.",
    "price": 200,
    "imageUrl": "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 10,
    "calories": 440,
    "rating": 4.96,
    "reviewCount": 590,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 807,
    "categoryId": 8,
    "name": "Chicken Chilly (8 pcs)",
    "description": "Boneless crispy chicken tossed in a fiery dark soya, garlic, and green chilli glaze with diced bell peppers and spring onions.",
    "price": 250,
    "imageUrl": "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 3,
    "preparationTimeMinutes": 12,
    "calories": 520,
    "rating": 4.98,
    "reviewCount": 710,
    "ingredients": [],
    "allergens": [
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 808,
    "categoryId": 8,
    "name": "Chicken Wings (5 pcs)",
    "description": "Juicy, smoky chicken wings glazed in a finger-licking barbecue and sweet chilli glaze, charred on the edges.",
    "price": 250,
    "imageUrl": "https://images.unsplash.com/photo-1527477321055-436158a2b0a5?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 2,
    "preparationTimeMinutes": 14,
    "calories": 540,
    "rating": 4.94,
    "reviewCount": 460,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 901,
    "categoryId": 9,
    "name": "Veg Chowmein",
    "description": "Wok-tossed hakka noodles with crunchy shredded cabbage, carrots, bell peppers, spring onions, and aromatic dark soya sauce.",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 10,
    "calories": 390,
    "rating": 4.87,
    "reviewCount": 380,
    "ingredients": [],
    "allergens": [
      "Gluten",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 902,
    "categoryId": 9,
    "name": "Egg Chowmein",
    "description": "Wok-tossed noodles scrambled with farm-fresh eggs, julienned vegetables, and aromatic Indo-Chinese wok spices.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 10,
    "calories": 440,
    "rating": 4.91,
    "reviewCount": 430,
    "ingredients": [],
    "allergens": [
      "Egg",
      "Gluten",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 903,
    "categoryId": 9,
    "name": "Chicken Chowmein",
    "description": "Tender shredded chicken pieces and noodles stir-fried on high flame with garlic, soya sauce, and fresh garden vegetables.",
    "price": 140,
    "imageUrl": "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 12,
    "calories": 490,
    "rating": 4.95,
    "reviewCount": 650,
    "ingredients": [],
    "allergens": [
      "Gluten",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 904,
    "categoryId": 9,
    "name": "Chicken Egg Chowmein",
    "description": "The ultimate combination of juicy chicken, fluffy scrambled eggs, and noodles tossed in high-heat wok seasonings.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 12,
    "calories": 530,
    "rating": 4.97,
    "reviewCount": 720,
    "ingredients": [],
    "allergens": [
      "Egg",
      "Gluten",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 905,
    "categoryId": 9,
    "name": "Chicken Double Egg Chowmein",
    "description": "Double farm-fresh eggs and juicy chicken pieces stir-fried with noodles for maximum protein and rich wok flavour.",
    "price": 160,
    "imageUrl": "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 12,
    "calories": 580,
    "rating": 4.98,
    "reviewCount": 590,
    "ingredients": [],
    "allergens": [
      "Egg",
      "Gluten",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1001,
    "categoryId": 10,
    "name": "Veg Fried Rice",
    "description": "Fragrant long-grain basmati rice wok-tossed with finely chopped french beans, carrots, sweet corn, and mild white pepper.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 10,
    "calories": 370,
    "rating": 4.88,
    "reviewCount": 340,
    "ingredients": [],
    "allergens": [
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1002,
    "categoryId": 10,
    "name": "Chicken Fried Rice",
    "description": "Classic wok-tossed aromatic basmati rice loaded with seasoned chicken cubes, spring onions, and garlic butter.",
    "price": 160,
    "imageUrl": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 12,
    "calories": 480,
    "rating": 4.94,
    "reviewCount": 580,
    "ingredients": [],
    "allergens": [
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1003,
    "categoryId": 10,
    "name": "Chicken Egg Fried Rice",
    "description": "Aromatic basmati rice stir-fried with juicy chicken chunks, scrambled eggs, and premium oriental herbs.",
    "price": 180,
    "imageUrl": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 12,
    "calories": 530,
    "rating": 4.96,
    "reviewCount": 610,
    "ingredients": [],
    "allergens": [
      "Egg",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1004,
    "categoryId": 10,
    "name": "Mixed Fried Rice",
    "description": "A grand celebratory mix of chicken, scrambled egg, and garden vegetables wok-tossed in signature secret spices.",
    "price": 200,
    "imageUrl": "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 14,
    "calories": 590,
    "rating": 4.98,
    "reviewCount": 690,
    "ingredients": [],
    "allergens": [
      "Egg",
      "Soy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1005,
    "categoryId": 10,
    "name": "Chicken Nuggets (8 pcs)",
    "description": "Crispy golden-crumbed tender chicken nuggets, juicy on the inside, served with hot garlic dip.",
    "price": 150,
    "imageUrl": "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 8,
    "calories": 380,
    "rating": 4.9,
    "reviewCount": 370,
    "ingredients": [],
    "allergens": [
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1006,
    "categoryId": 10,
    "name": "Chicken Cutlet (3 pcs)",
    "description": "Traditional heritage-style spiced minced chicken patties breaded in coarse crumbs and fried deep golden crisp, served with kasundi mustard.",
    "price": 160,
    "imageUrl": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 1,
    "preparationTimeMinutes": 10,
    "calories": 420,
    "rating": 4.95,
    "reviewCount": 440,
    "ingredients": [],
    "allergens": [
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1101,
    "categoryId": 11,
    "name": "Coke / Sprite",
    "description": "Chilled classic carbonated can (330ml) served over crystal ice with a slice of fresh lemon.",
    "price": 50,
    "imageUrl": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 2,
    "calories": 140,
    "rating": 4.8,
    "reviewCount": 220,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1102,
    "categoryId": 11,
    "name": "Masala Coke / Sprite",
    "description": "A spicy desi twist: ice-cold soda spiked with roasted cumin, black salt, chaat masala, and fresh lime juice.",
    "price": 70,
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 3,
    "calories": 150,
    "rating": 4.92,
    "reviewCount": 380,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1103,
    "categoryId": 11,
    "name": "Fresh Lime Soda",
    "description": "Zesty fresh lime juice shaken with sparkling soda and your choice of sweet, salted, or mixed syrup.",
    "price": 60,
    "imageUrl": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 3,
    "calories": 85,
    "rating": 4.89,
    "reviewCount": 410,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1104,
    "categoryId": 11,
    "name": "Red Bull Energy Drink",
    "description": "Chilled 250ml can of Red Bull energy drink served with ice.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1543253687-c931c8e01820?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 2,
    "calories": 110,
    "rating": 4.85,
    "reviewCount": 190,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1105,
    "categoryId": 11,
    "name": "Green Mint Cooler",
    "description": "Invigorating muddled garden mint, lime wedges, simple syrup, and sparkling soda over crushed ice.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 95,
    "rating": 4.91,
    "reviewCount": 280,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1106,
    "categoryId": 11,
    "name": "Virgin Mojito",
    "description": "The classic refresher: muddled fresh mint sprigs, lime chunks, cane sugar, and chilled club soda over crushed ice.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 110,
    "rating": 4.95,
    "reviewCount": 620,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1107,
    "categoryId": 11,
    "name": "Blue Lagoon",
    "description": "Vibrant electric blue curacao syrup shaken with lemon-lime soda, citrus twist, and crushed crystal ice.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 130,
    "rating": 4.94,
    "reviewCount": 490,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1108,
    "categoryId": 11,
    "name": "Green Apple Mojito",
    "description": "Crisp green apple puree muddled with fresh mint, lime juice, and fizzy soda for a tart-sweet sparkle.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 125,
    "rating": 4.92,
    "reviewCount": 340,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1109,
    "categoryId": 11,
    "name": "Fresh Orange Mint",
    "description": "Sun-ripened orange juice blended with crushed garden mint leaves and sparkling soda over ice.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 115,
    "rating": 4.9,
    "reviewCount": 260,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1110,
    "categoryId": 11,
    "name": "Kala Khatta Mocktail",
    "description": "The timeless nostalgic Indian street favourite: tangy jamun syrup with black salt, roasted cumin, and lemon fizz.",
    "price": 130,
    "imageUrl": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 120,
    "rating": 4.96,
    "reviewCount": 430,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 1201,
    "categoryId": 12,
    "name": "Sweet Lassi",
    "description": "Traditional Punjabi churned fresh whole-milk yogurt, infused with cardamom, topped with thick clotted cream (malai).",
    "price": 80,
    "imageUrl": "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 240,
    "rating": 4.93,
    "reviewCount": 390,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1202,
    "categoryId": 12,
    "name": "Mango Lassi",
    "description": "Rich creamy yogurt blended with sweet Alphonso mango pulp and saffron notes, served chilled.",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1546889988-d63c5a610443?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 280,
    "rating": 4.98,
    "reviewCount": 580,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1203,
    "categoryId": 12,
    "name": "Pineapple Lassi",
    "description": "Tangy-sweet crushed pineapple churned with thick probiotic yogurt and a dash of mint.",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 250,
    "rating": 4.88,
    "reviewCount": 210,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1204,
    "categoryId": 12,
    "name": "Strawberry Lassi",
    "description": "Fresh sweet strawberry puree folded into thick velvety churned yogurt, rich, smooth, and vibrant.",
    "price": 100,
    "imageUrl": "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 260,
    "rating": 4.91,
    "reviewCount": 260,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1205,
    "categoryId": 12,
    "name": "Banana Lassi",
    "description": "Fresh ripe banana blended with thick curd, wild honey, and crushed cardamom for natural creamy energy.",
    "price": 80,
    "imageUrl": "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 230,
    "rating": 4.86,
    "reviewCount": 180,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1301,
    "categoryId": 13,
    "name": "Oreo Frappe",
    "description": "Rich blended iced espresso with crushed Oreo cookies, milk, and chocolate fudge topped with whipped cream.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 380,
    "rating": 4.96,
    "reviewCount": 420,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1302,
    "categoryId": 13,
    "name": "Biscoff Frappe",
    "description": "Creamy frappe churned with authentic Lotus Biscoff spread and biscuit crumbs, finished with whipped cream.",
    "price": 190,
    "imageUrl": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 410,
    "rating": 4.99,
    "reviewCount": 540,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1303,
    "categoryId": 13,
    "name": "Caramel Frappe",
    "description": "Sweet golden buttery caramel blended with espresso, chilled milk, and ice, drizzled with caramel sauce.",
    "price": 190,
    "imageUrl": "https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 360,
    "rating": 4.93,
    "reviewCount": 310,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1304,
    "categoryId": 13,
    "name": "Coffee Mocha Frappe",
    "description": "Decadent dark chocolate mocha and espresso blended icy cold, topped with dark chocolate chips and cream.",
    "price": 190,
    "imageUrl": "https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 390,
    "rating": 4.95,
    "reviewCount": 390,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1305,
    "categoryId": 13,
    "name": "Matcha Frappe",
    "description": "Japanese green tea matcha blended with sweet cream and ice, topped with a dusting of matcha powder.",
    "price": 190,
    "imageUrl": "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 310,
    "rating": 4.94,
    "reviewCount": 290,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1306,
    "categoryId": 13,
    "name": "Strawberry Frappe",
    "description": "Sweet berry cream dream: ripe strawberries blended with ice and milk, topped with whipped cream.",
    "price": 170,
    "imageUrl": "https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 330,
    "rating": 4.89,
    "reviewCount": 240,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1307,
    "categoryId": 13,
    "name": "Blueberry Frappe",
    "description": "Wild blueberry compote blended icy smooth with rich milk, topped with blueberry drizzle.",
    "price": 190,
    "imageUrl": "https://images.unsplash.com/photo-1626078436892-0f04f2f4e8b3?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 340,
    "rating": 4.92,
    "reviewCount": 270,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1308,
    "categoryId": 13,
    "name": "Mango Frappe",
    "description": "Tropical mango frost sensation: sweet mango pulp blended with vanilla ice and cream.",
    "price": 160,
    "imageUrl": "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 5,
    "calories": 320,
    "rating": 4.91,
    "reviewCount": 260,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1309,
    "categoryId": 13,
    "name": "Vanilla Ice Cream (3 scoops)",
    "description": "Three generous scoops of velvety classic Madagascar vanilla ice cream served in a frosted dessert bowl.",
    "price": 120,
    "imageUrl": "https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 2,
    "calories": 260,
    "rating": 4.88,
    "reviewCount": 310,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 1401,
    "categoryId": 14,
    "name": "Arrabbiata Pasta (Veg)",
    "description": "Penne pasta tossed in a fiery San Marzano tomato sauce infused with fresh garlic, extra virgin olive oil, red chilli flakes, and fresh basil.",
    "price": 229,
    "imageUrl": "https://images.unsplash.com/photo-1621996346565-e3d5d6281699?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 2,
    "preparationTimeMinutes": 12,
    "calories": 420,
    "rating": 4.94,
    "reviewCount": 460,
    "ingredients": [
      "Penne Pasta",
      "San Marzano Tomato Sauce",
      "Garlic",
      "Extra Virgin Olive Oil",
      "Chilli Flakes",
      "Fresh Basil"
    ],
    "allergens": [
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1402,
    "categoryId": 14,
    "name": "Arrabbiata Pasta (Chicken)",
    "description": "Penne pasta with tender grilled seasoned chicken strips tossed in bold spicy tomato Arrabbiata sauce and Italian herbs.",
    "price": 279,
    "imageUrl": "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 2,
    "preparationTimeMinutes": 14,
    "calories": 530,
    "rating": 4.98,
    "reviewCount": 620,
    "ingredients": [
      "Grilled Chicken Breast",
      "Penne Pasta",
      "Tomato Sauce",
      "Garlic",
      "Chilli Flakes",
      "Italian Herbs"
    ],
    "allergens": [
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1403,
    "categoryId": 14,
    "name": "Alfredo Pasta (Veg)",
    "description": "Fettuccine or penne bathed in a luxurious creamy white sauce made from pure butter, fresh cream, garlic, and aged Parmesan cheese.",
    "price": 249,
    "imageUrl": "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 12,
    "calories": 560,
    "rating": 4.96,
    "reviewCount": 510,
    "ingredients": [
      "Pasta",
      "Parmesan Cheese",
      "Heavy Cream",
      "Butter",
      "Garlic",
      "Oregano"
    ],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 1404,
    "categoryId": 14,
    "name": "Alfredo Pasta (Chicken)",
    "description": "Rich & creamy Parmesan white sauce pasta tossed with herb-marinated grilled chicken breast slices and cracked black pepper.",
    "price": 299,
    "imageUrl": "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": true,
    "isBestSeller": true,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 14,
    "calories": 680,
    "rating": 4.99,
    "reviewCount": 780,
    "ingredients": [
      "Grilled Herb Chicken",
      "Pasta",
      "Aged Parmesan",
      "Heavy Cream",
      "Garlic Butter"
    ],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 9901,
    "categoryId": 99,
    "name": "Garlic Bread (2 pcs)",
    "description": "Crispy golden artisan baguette slices toasted with rich garlic herb butter.",
    "price": 59,
    "imageUrl": "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": false,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 160,
    "rating": 4.92,
    "reviewCount": 410,
    "ingredients": [],
    "allergens": [
      "Dairy",
      "Gluten"
    ],
    "customizationGroups": []
  },
  {
    "id": 9902,
    "categoryId": 99,
    "name": "Extra Cheese Topping",
    "description": "Generous portion of melted 100% mozzarella and cheddar cheese blend.",
    "price": 49,
    "imageUrl": "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 2,
    "calories": 120,
    "rating": 4.95,
    "reviewCount": 530,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  },
  {
    "id": 9903,
    "categoryId": 99,
    "name": "Extra Grilled Chicken",
    "description": "Portion of tender herb-seasoned juicy grilled chicken breast chunks.",
    "price": 79,
    "imageUrl": "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": false,
    "isNonVeg": true,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 4,
    "calories": 180,
    "rating": 4.96,
    "reviewCount": 480,
    "ingredients": [],
    "allergens": [],
    "customizationGroups": []
  },
  {
    "id": 9904,
    "categoryId": 99,
    "name": "Ice Cream Add On (1 scoop)",
    "description": "One scoop of rich vanilla ice cream to top your shakes, frappes, or desserts.",
    "price": 30,
    "imageUrl": "https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=80",
    "isVegetarian": true,
    "isNonVeg": false,
    "isJain": false,
    "isGlutenFree": true,
    "isChefSpecial": false,
    "isBestSeller": false,
    "isAvailable": true,
    "spiceLevel": 0,
    "preparationTimeMinutes": 1,
    "calories": 90,
    "rating": 4.9,
    "reviewCount": 340,
    "ingredients": [],
    "allergens": [
      "Dairy"
    ],
    "customizationGroups": []
  }
];

const MOCK_COUPONS = [
  { code: 'CHAIADDAA50', title: 'Flat ₹50 Off', discountAmount: 50, minOrderAmount: 200, description: 'Get ₹50 off on your first Chai Addaa order above ₹200.' },
  { code: 'ADDAA100', title: 'Chai & Bites ₹100 Off', discountAmount: 100, minOrderAmount: 400, description: 'Get ₹100 off on orders above ₹400.' },
  { code: 'BOBAFEAST', title: 'Boba & Frappe Special', discountAmount: 75, minOrderAmount: 300, description: 'Exclusive ₹75 discount on Boba, Frappes and Coolers above ₹300.' },
  { code: 'FAMILY200', title: 'Addaa Grand Feast', discountAmount: 200, minOrderAmount: 800, description: 'Get ₹200 off on large group dining orders above ₹800.' }
];

const MOCK_FAQS = [
  { question: 'What are your café hours?', answer: 'We are open every day from 10:00 AM to 11:00 PM for dine-in, takeaway, and digital ordering.', category: 'Dining' },
  { question: 'Do you offer pure vegetarian / Jain options?', answer: 'Yes! All our teas, boba, shakes, fries, veg pasta, and veg appetizers are 100% vegetarian. Check the green Veg indicator on the menu.', category: 'Food' },
  { question: 'Is High-Speed Wi-Fi available for working?', answer: 'Yes, we provide complimentary high-speed 5G Wi-Fi for all our guests (SSID: SiliguriChaiAddaa-5G).', category: 'General' },
  { question: 'How do I place an order from my table?', answer: 'Simply scan the QR code on your table, add your favorite items to cart, and hit Place Order — no app installation needed!', category: 'Ordering' }
];

const MOCK_GALLERY = [
  { title: 'The Chai Addaa Ambiance', description: 'Cozy boho decor, fairy lights, and warm wooden vibes.', imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80', category: 'Ambiance' },
  { title: 'Signature Masala Chai', description: 'Freshly brewed kadak tea in traditional earthen style.', imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80', category: 'Chai' },
  { title: 'Boba & Matcha Specials', description: 'Handcrafted Japanese Uji matcha and popping boba teas.', imageUrl: 'https://images.unsplash.com/photo-1558857563-b37cfb4226f8?auto=format&fit=crop&w=800&q=80', category: 'Boba' }
];

const seedDB = async () => {
  try {
    await connectDB();
    await Category.deleteMany();
    await MenuItem.deleteMany();
    await Coupon.deleteMany();
    await Faq.deleteMany();
    await Gallery.deleteMany();

    await Category.insertMany(MOCK_CATEGORIES);
    await MenuItem.insertMany(MOCK_MENU_ITEMS);
    await Coupon.insertMany(MOCK_COUPONS);
    await Faq.insertMany(MOCK_FAQS);
    await Gallery.insertMany(MOCK_GALLERY);

    console.log(`Database Seeded Successfully! Added ${MOCK_CATEGORIES.length} Categories & ${MOCK_MENU_ITEMS.length} Culinary Items.`);
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedDB();
